### ISSUE TITLE
No updates called on state changes.

### ISSUE THREAD

**Issue by Cynosphere** [TheQwertiest/foo_discord_rich#1]
State changes such as pausing do not update the text at all, rendering functions like `%ispaused%` useless, thus no way for users to express a paused state at all aside from the time remaining being hidden, if its even enabled.

**Comment by Cynosphere** [comment]
Would also be nice to see small_icon being used as playing state also, like other RPC extensions.

**Comment by TheQwertiest** [comment]
Note: formatting won't be triggered on track duration change (i.e. every second), since Discord API has rather strict limitations on presence update requests frequency (one update per 15 seconds).
