### ISSUE TITLE
Default pause behaviour

### ISSUE THREAD

**Issue by a1ph0r** [TheQwertiest/foo_discord_rich#10]
Thanks for this great plugin. Would it be possible to either change the default behaviour, or add an option, to change the pausing behaviour. Currently when pausing Foobar2k the Playing status remains @ Discord, whereas Discords built-in Spotify support clears the status when pausing a track. Could you either change the plugin's behaviour, or add an option to stop displaying the status on pause please?

**Comment by endalchemist** [comment]
This would be something I would be interested in seeing as well, if the possibility exists.

**Comment by TheQwertiest** [comment]
Will be added in the future release
