### ISSUE TITLE
Possebility to add a option to display current time with length of the track.

### ISSUE THREAD

**Issue by AntonShad** [TheQwertiest/foo_discord_rich#11]
I have been wanting to have a setting to display in the presence the elapsed time with the length of the track itself. It would be like "%elapsedTime% / %trackLength%". This would be so that if other users look at the presence they can see the information that the current elapsed and remaining time options give using math themselves.

**Comment by TheQwertiest** [comment]
Regretfully, it can't be done: Discord Rich Presence API only allows either of the two: elapsed time and remaining time. It does not allow to display them simultaneously =(
