### ISSUE TITLE
Live Change Playback Status Image

### ISSUE THREAD

**Issue by killerfong** [TheQwertiest/foo_discord_rich#14]
When I disable Foobar2000 image and open playback status image it didn't show up cover art image.
It should display cover art for the music right?
![image](https://user-images.githubusercontent.com/26829219/73115790-01f0e500-3f66-11ea-810b-bec447c9e0a5.png)
![image](https://user-images.githubusercontent.com/26829219/73115794-0f0dd400-3f66-11ea-958c-75c622f6f640.png)

**Comment by TheQwertiest** [comment]
> It should display cover art for the music right?

No, it shouldn't =)
Displaying album art is currently impossible. See #6 for more info.
