### ISSUE TITLE
Old Foobar version still displayed in Rich presence

### ISSUE THREAD

**Issue by UmbraVivens** [TheQwertiest/foo_discord_rich#15]
foobar is currently in v1.5.1, but the rich presence still says v1.4.6
![image](https://user-images.githubusercontent.com/54699529/73260463-30013f80-4187-11ea-881d-01ec60b96ce5.png)
![image](https://user-images.githubusercontent.com/54699529/73260508-44453c80-4187-11ea-9d7e-51c328f49240.png)

**Comment by TheQwertiest** [comment]
Are you sure you are using `foo_discord_rich` component? Since there are at least two other fb2k components for Discord integration (and they all have similar names).
My component does not display fb2k version.

**Comment by UmbraVivens** [comment]
uh i just realised, it appears the version only displays when i idle on Stop. sorry this might be unrelated to the component after all

**Comment by TheQwertiest** [comment]
No problems =)
