### ISSUE TITLE
Add support for custom hover-text

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_discord_rich#17]
See https://hydrogenaud.io/index.php?topic=116860.msg981813#msg981813

**Comment by noiverre** [comment]
Any updated on this?

**Comment by TheQwertiest** [comment]
In a way this feature was implemented.
Hover text and bottom text now share the same value.
This means that you can't setup only one of them though... (this is due to the way "Listening activity" is handled by Discord)
We can only hope that Discord separates these values in the future...
