### ISSUE TITLE
custom images don't show up

### ISSUE THREAD

**Issue by SimonTheFoxcoon** [TheQwertiest/foo_discord_rich#18]
no matter how the images are set up in discord developers page, even keeping the same default names the plugin sets doesn't work when i use my own app, the client id is set correctly. i've even tried different image names, and no images show up. resetting the config for the plugin makes the default show up like it should. another person i know did the same, and it's working for them.
![image](https://user-images.githubusercontent.com/38541316/80031461-15a5dc00-84c0-11ea-9936-2fb9600ca90c.png)

**Comment by SimonTheFoxcoon** [comment]
nvm, closing this, discord api had issues the other day and it just seems to work now?

**Comment by Galixte** [comment]
Hi @SimonFoxcoon @TheQwertiest where is documentation to customize images?

* Do I change them in a particular folder on my HDD/SSD?
* Do I change by using my own Discord APP ID from Discord Rich preferences in Foobar2K, then by setting up some settings in Developer APP on Discord? But where is the tutoriel to do that especially to set images?

Regards.

**Comment by TheQwertiest** [comment]
@Galixte , see https://hydrogenaud.io/index.php?topic=116860.msg975663#msg975663
