### ISSUE TITLE
The option "Disable Rich Presence when paused" doesn't work

### ISSUE THREAD

**Issue by Baconz2** [TheQwertiest/foo_discord_rich#19]
Hey all,
I was messing with settings in foobar and all of a sudden, "Disable Rich Presence when paused" randomly stopped working. 
![image](https://user-images.githubusercontent.com/46719718/90211020-72494180-dda4-11ea-8160-b392eeed145b.png) 
![image](https://user-images.githubusercontent.com/46719718/90211076-8d1bb600-dda4-11ea-82f1-dead23777c1b.png)
Screenshot of that. I tried resetting the settings, reinstalling the plugin, nothing's worked. Ideas?

**Comment by Baconz2** [comment]
Update: Apparently it just randomly started working after a couple hours. Sorry about that.

**Comment by Baconz2** [comment]
Weirdly, it seems to just randomly work and stop working.

**Comment by Baconz2** [comment]
I really do not know what is going on here.

**Comment by TheQwertiest** [comment]
It should be noted that there is a refresh rate limit. I.e. if you change the info too often, it will throttle it for some time (e.g. by pausing/unpausing a lot in a short amount of time).

This refresh limit is applied to any Discord Presence refresh operation.

PS: I can't be sure if this is actually the source of your problems though.

**Comment by Baconz2** [comment]
That doesn't *seem* to be the problem, because I can't even get the rich presence to disable when paused anymore, weirdly enough.

**Comment by TheQwertiest** [comment]
Most likely a duplicate of #21 . Please reopen if it's not fixed for you in the nightly build.
