### ISSUE TITLE
Stopping playback restores presence that was disabled due to pause

### ISSUE THREAD

**Issue by xKevin04** [TheQwertiest/foo_discord_rich#21]
Steps to reproduce:

1. Enable the option "Disable Rich Presence when paused"
2. Play a track -> status will show in Discord
3. Pause the track -> status will be removed from Discord
4. Stop the track -> status will be shown as paused in Discord

**Comment by TheQwertiest** [comment]
That's really weird, I'll look into it

**Comment by TheQwertiest** [comment]
Thanks for the report, should be fixed now.
