### ISSUE TITLE
Option to not overwrite present status

### ISSUE THREAD

**Issue by xKevin04** [TheQwertiest/foo_discord_rich#22]
If I'm playing a game and listening to music via foobar2000 at the same time, Rich Presence will always overwrite my game activity. I'd rather have the listen status only show up when there's no other game activity in Discord.

I don't know if it's possible at all via the Discord API, but if constant pinging would be needed to obtain the current status, it would suffice to do it on track change or other manual activity in fb2k.

**Comment by TheQwertiest** [comment]
Regretfully, Discord API does not provide any way to detect if another Rich Presence is active. I.e. nothing can be done from my end.
