### ISSUE TITLE
Fall back to song artist if album artist not available

### ISSUE THREAD

**Issue by dninemfive** [TheQwertiest/foo_discord_rich#24]
As an enhancement, it'd be nice if the displayed artist could show up as the one for the song if the song artist and album artist differ. For example, right now, the song "Vengeance" by Perturbator off the Hotline Miami OST shows up as 
```
Various Artists: Hotline Miami OST
Vengeance
```
when it would be give more info if it said either
```
Perturbator: Hotline Miami OST
Vengeance
```
or (more correctly)
```
Hotline Miami OST
Perturbator: Vengeance
```

**Comment by Jengamon** [comment]
Use `%track artist%` to indicate track artists, so to get:
```
Hotline Miami OST
Pertubator: Vengence
```
in your rich Discord presence,

set top text field (On the `Tools -> Rich Discord Presence` preference page) to:
```
[[$if(%track artist%,,%album artist%): ][%album%]]
```

and bottom to:
```
[%track artist%: ][%title%]
```

Examples:
*Where album artist =/= artist*:
![image](https://user-images.githubusercontent.com/1479994/99728003-c0966c80-2a86-11eb-9a6a-30c12f2c2df3.png)
*Where album artist == artist*: (This song was a single where the album name was the name of the song, so...)
![image](https://user-images.githubusercontent.com/1479994/99728106-e754a300-2a86-11eb-82da-3ee09ed267eb.png)

**Comment by dninemfive** [comment]
Thank you! This works great.
