### ISSUE TITLE
Assets for "repeat" etc.

### ISSUE THREAD

**Issue by Visual917** [TheQwertiest/foo_discord_rich#27]
On Spotify you have small image assets for repeat, loop etc. besides the Play and Pause. Is there a way we can integrate these too?

Also, do you have Discord? I can't seem to reach you anywhere and you're not active here :(

**Comment by TheQwertiest** [comment]
Not sure what you mean. Does Spotify integration has different icons for different playback modes? Can you attach a screenshot with an example?

**Comment by tort-oise** [comment]
I actually know what this is about, it's probably this: 
![image](https://user-images.githubusercontent.com/81963124/190594244-01f9b041-fc79-48cb-b6d5-55b09f5e18b8.png)
The small icons on the right and left. Shuffle, loop, etc. I'm pretty sure this person accidentally mistook this project for foobar2000 itself, being angry that this isn't in foobar 
![image](https://user-images.githubusercontent.com/81963124/190594427-a5c0f15f-8859-48a4-bda5-b9b79b9c7a0e.png)
.

**Comment by Visual917** [comment]
> I actually know what this is about, it's probably this: ![image](https://user-images.githubusercontent.com/81963124/190594244-01f9b041-fc79-48cb-b6d5-55b09f5e18b8.png) The small icons on the right and left. Shuffle, loop, etc. I'm pretty sure this person accidentally mistook this project for foobar2000 itself, being angry that this isn't in foobar ![image](https://user-images.githubusercontent.com/81963124/190594427-a5c0f15f-8859-48a4-bda5-b9b79b9c7a0e.png) .

No I know this project is for the Discord rich presence for foobar2000 ahahah and why would I be angry??

All I was saying is we could have a small icon on Discord indicating the song is on loop/shuffle etc. That's it.

**Comment by tort-oise** [comment]
Is it possible for you to give this an "enhancement" label, then? Or is that something that only @TheQwertiest can do? I think your suggestion can be viable, but I'm unsure whether it's possible or not due to inherent Discord limitations.

If you had this idea, then where would you place these buttons?

**Comment by Visual917** [comment]
There is a small icon section for rich presence apps. I have developed for it before. So it is possible..

**Comment by tort-oise** [comment]
Is that icon section not reserved for the play/pause button? In the bottom right. 
![image](https://user-images.githubusercontent.com/81963124/191439153-5cbc22f7-8f44-4b57-a8a7-0ca45669a207.png)

How would we make play/shuffle buttons fit in here? Hmmm..

**Comment by Visual917** [comment]
You wouldn't show the play icon obviously

**Comment by tort-oise** [comment]
Giving up a play icon for a loop/shuffle icon, of which can't be displayed in the same little tab? I dunno, mate, I'm not really into it.

**Comment by Visual917** [comment]
It could be optional or could have a special ShufflePlay button

**Comment by TheQwertiest** [comment]
The best I could do is to allow fb2k queries for image.
But due to discord API limitations, it can't be refreshed frequently anyway (not higher than once in ~15 seconds), thus, IMO, the feature would me more confusing than helpful for most users,
