### ISSUE TITLE
How to get discord application token

### ISSUE THREAD

**Issue by SilkTofu** [TheQwertiest/foo_discord_rich#30]
How to get discord application token manually as i am running multiple instances of discord in one system, thanks in advance

**Comment by NoobChester** [comment]
Not sure what you mean by that, the discord application token used by the component developer is 507982587416018945.
I don't think foobar2000 itself has a token.

**Comment by tort-oise** [comment]
I run multiple instances of discord in one system too, and the status shows up on every single one. Magic!
If you want to disable it on one account, either:
- disable _"Show current activity as a status message"_ in Discord's settings on that account
- add a different activity
- make that account offline

If none of these solve your problem, then please make your issue about that instead. Vague things like these will solve nothing.

**Comment by SilkTofu** [comment]
yes
