### ISSUE TITLE
How to configure Discord side?

### ISSUE THREAD

**Issue by LeeThompson** [TheQwertiest/foo_discord_rich#33]
The docs are missing how to set it up in Discord...

**Comment by kozaka-tv** [comment]
Yeah! I just tried to set it up, but after install it just not works.

**Comment by kozaka-tv** [comment]
I found out! :)

In Discord --> User Settings --> Activity Status >> Display current activity as a status message.

![image](https://user-images.githubusercontent.com/4964462/132092854-220639bd-e533-4513-8d5b-e380871dd798.png)

**Comment by kozaka-tv** [comment]
![image](https://user-images.githubusercontent.com/4964462/132092877-984c0831-90c4-4286-990a-7eedd4806eba.png)

**Comment by tort-oise** [comment]
If your issue is solved, please close it. 

For that matter, I don't even think there's any discord-side setup besides the "Display current activity as a status message". The only other modification can be done through the module itself.

**Comment by kozaka-tv** [comment]
I think, the original problem is not solved. There is no documentation how to setup the whole thing in Foobar and Discord. Just the installation.

**Comment by tort-oise** [comment]
It's enabled by default. If someone disables it, they should know that it needs to be enabled for rich presence to be enabled. Nonetheless, it can just be added in the description of the component or the GitHub page.

**Comment by kozaka-tv** [comment]
Thank you! That would be great! <3

I think I had it that time disabled, and that's the why I had trouble to set it correctly up.

**Comment by TheQwertiest** [comment]
Added more instructions to Installation and FAQ pages
