### ISSUE TITLE
Rich Presence Doesn't Auto Update / Adding Manually breaks it as well 

### ISSUE THREAD

**Issue by n3rv** [TheQwertiest/foo_discord_rich#35]
I'm using foo_discord_rich: v.1.2.0
foobar: v1.6.7
Discord: Stable 103871 (e0f6e26) 
Host: 1.0.9003 Windows 10 64-Bit (10.0.19043)

Discord can definitely see that foobar is playing if I go into Activity Status, but if I add it manually though that it will never update past that initial check. 

With nothing playing: 
![image](https://user-images.githubusercontent.com/8541977/140662985-c9aa843e-9eb9-4936-8616-6b0671b68c12.png)

With something playing: 
![image](https://user-images.githubusercontent.com/8541977/140662935-425ad625-19fd-4f2e-a4b8-f19a7e8db077.png)

**Comment by TheQwertiest** [comment]
Don't add it manually, it should work automatically.

**Comment by tort-oise** [comment]
Adding onto this, I wish that you close this issue, for the reason below:

- The custom foobar status should not be added manually. 
- The foobar module automatically sends the Rich Presence info to your client, making it show up in your activity when online.
- While yes, it doesn't show up properly under the Activity Status settings, the point is that it doesn't need to show up. It shows up anyways.

Or at the very least, should. If it is not showing up when you're online and currently listening, then please make this issue about that instead. If any of these options answer your question, please close this issue instead.

**Comment by KODETTO** [comment]
For anybody else who wound up here, ensure that in Discord -> User Settings -> Activity Privacy, "Display current activity as a status message" is set to blue checkmark (ON). This is what allows Rich Presence to communicate with the Discord app. I'd turned mine off a year ago and completely forgotten until today.

**Comment by RadegasTCZ** [comment]
About that "Rich Presence Doesn't Auto Update" part of the title, it seems it only updates only on song change, which might be okay, but if I have a variable that I want to have refreshed, for example bitrate, you're out of luck. Maybe having the option to refresh the status like every 10 seconds would be nice.
