### ISSUE TITLE
Could more status lines be added?

### ISSUE THREAD

**Issue by Okarisu** [TheQwertiest/foo_discord_rich#36]
I'd lilke to put more information to my status bar on Discord such as artist name along with progress bar, but there are only 2 lines available, which makes everything a mess and only part of content is displayed.

![obrazek](https://user-images.githubusercontent.com/77163811/147855442-14258657-4c5e-4913-89c0-51ed4af1297b.png)

**Comment by TheQwertiest** [comment]
Nope, Discord API allows only two separate lines
