### ISSUE TITLE
Name of component misspelled

### ISSUE THREAD

**Issue by karasuhebi** [TheQwertiest/foo_discord_rich#41]
Name of component shows up as Discord Rich Presen**s**e instead of Discord Rich Presence.
![lhuMfGI](https://user-images.githubusercontent.com/6857825/193191866-d79b80d5-f798-4300-8ebe-b3e4d567c17b.png)

**Comment by yunooooo** [comment]
clap if u care..

**Comment by TheQwertiest** [comment]
*clap*

**Comment by karasuhebi** [comment]
Let's go!!

**Comment by TheQwertiest** [comment]
It was actually fixed several years by @b1scoito : https://github.com/TheQwertiest/foo_discord_rich/commit/ec8d168008488bd57ed6c8c394d140d07d0d8b21
