### ISSUE TITLE
Error: This component was built for a different processor architecture.

### ISSUE THREAD

**Issue by lopes143** [TheQwertiest/foo_discord_rich#45]
Hello
Today I tried to install the latest version of the plugin on Foobar2000 2.0 x64 on Windows 11 but I get this error:

`Could not load component "foo_discord_rich.fb2k-component": This component was built for a different processor architecture.`

Any idea of what could it be?
Sorry for my bad English

**Comment by beefcat666** [comment]
The component needs to be re-compiled against the [new SDK](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Development:SDK_2022-08-10_Release_Notes) with support for the new 64-bit version of foobar.

**Comment by JDJGInc** [comment]
It's a little annoying because any application that's built with an old sdk will be flagged.

**Comment by aaronliu0130** [comment]
Does anyone know how one could recompile the component themselves?

**Comment by fritojay** [comment]
https://github.com/fritojay/foo_discord_rich/releases/tag/v1.2.1 has a 64 bit build.

**Comment by aaronliu0130** [comment]
Sweet! Could you build it with https://github.com/s0hv/foo_discord_rich/tree/cover-art-images ?

**Comment by fritojay** [comment]
Have them send me a MR and ill build it.

**Comment by aaronliu0130** [comment]
"MR"?

**Comment by fritojay** [comment]
A Pull Request for the feature in my repo. I guess I could just merge it blindly and see what happens.

**Comment by aaronliu0130** [comment]
hmm usually people call these PRs, done

**Comment by aaronliu0130** [comment]
I can't do that. You could switch your origin to s0hv and just pull it and merge the cover art branch into master

**Comment by aaronliu0130** [comment]
Actually I can also fork that repo and open a pull request to you, hold on

**Comment by aaronliu0130** [comment]
@fritojay this doesn't update
![image](https://user-images.githubusercontent.com/11874211/236652575-eca3ef67-11f2-43f3-92a4-235112889e25.png)

**Comment by fritojay** [comment]
@aaronliu0130 let's create an issue under my repo and discuss it there. FWIW, it is updating for me.

**Comment by aaronliu0130** [comment]
@fritojay your repo doesn't have issues, it only has pull requests.

**Comment by aaronliu0130** [comment]
Also it doesn't happen anymore for some reason.

**Comment by TheQwertiest** [comment]
duplicate #39
