### ISSUE TITLE
incompatibility error while trying to install 

### ISSUE THREAD

**Issue by karimHI** [TheQwertiest/foo_discord_rich#49]
Could not load component "foo_discord_rich.fb2k-component": This component was built for a different processor architecture.
i'm USING normal 64bit 
IT ONLY OCCURS WHEN USING LATEST FOBAR VERSION 2.0
1.6 AND OLDER STILL WORKING

![image](https://github.com/TheQwertiest/foo_discord_rich/assets/70208636/aa29c98b-cdbe-450e-848d-4674f1728b53)

**Comment by HumbleDeer** [comment]
That's because the component hasn't been updated yet. Foobar2000 used to be 32bit only.
I'm looking at compiling it for 64bit myself, as I'm desiring this component again.

**Comment by RadegasTCZ** [comment]
Foobar2000 still has 32bit builds available, so I downloaded mine in 32bit edition and works as expected. I didn't notice any difference in functionality I need between the two so.
![image](https://github.com/TheQwertiest/foo_discord_rich/assets/22341950/7ee8c5a8-1325-4a60-9f53-b9d4595ed701)
