### ISSUE TITLE
Invalid handling of ' and \ characters

### ISSUE THREAD

**Issue by Dogeisbest** [TheQwertiest/foo_discord_rich#5]
Let's say I wanted to say at the top, "I'm listening to". I can't do so, because, with the way you have it set up, the quotations are ', so it thinks that it's the end of the statement. I can't do \ either, because it thinks it's breaking it.
![image](https://user-images.githubusercontent.com/29840719/50399485-c7f35500-074d-11e9-9c01-1280b9fa4c3f.png)
![image](https://user-images.githubusercontent.com/29840719/50399496-dc375200-074d-11e9-8756-d614f5e28b6b.png)
![image](https://user-images.githubusercontent.com/29840719/50399506-f2451280-074d-11e9-9054-62360ccad1b0.png)

**Comment by TheQwertiest** [comment]
Hm... I'll look into it. Thanks for the bug report!

**Comment by TheQwertiest** [comment]
Not a bug: component uses [fb2k title formatting rules](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#Syntax). In your case you have to use two single quotes `'` to escape formatting.
