### ISSUE TITLE
sample rate for DSD64 is wrong

### ISSUE THREAD

**Issue by SprayJuice** [TheQwertiest/foo_discord_rich#51]
When playing a DSD64 file, the sample rate is shown as 282.24 kHz when it is supposed to be 2822.4 kHz

![sample rate](https://github.com/TheQwertiest/foo_discord_rich/assets/85349059/3462ca92-be9b-44a8-bcfb-918d97ab84b3)

**Comment by TheQwertiest** [comment]
This query is not a default value in foo_discord_rich, thus there is nothing to fix in the component itself.
You may consult [official foobar2000 doc](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference) or ask for help in hydrogenaud.io forum though .
