### ISSUE TITLE
Component no longer seems to work

### ISSUE THREAD

**Issue by ULTRACOMFY** [TheQwertiest/foo_discord_rich#56]
It seems like the component is broken. While it has always been fine, I just now realized that my playing info no longer shows up in Discord. I tried to turn the "Share Activity" setting off and on, as well as the "Share with Large Servers by Default" setting, verified with other games that it still works _at all_ (Rocket League worked), the foobar playing status does not work on either of my two Windows machines that had been perfectly fine before and showed the status.

**Comment by TheQwertiest** [comment]
Nothing that can be done from component side: it uses very basic API that has almost no points of customization (heck, it basically consists of three methods: `Register`, `UpdateRichPresence`, `Unregister`).

You may try performing various steps from this issue though: https://github.com/TheQwertiest/foo_discord_rich/issues/28

**Comment by ULTRACOMFY** [comment]
Okay so I just worked into it a bit. I know why it stopped working, but I don't think this is how it should work. So I was in the Discord application developer portal and deleted an app I had created a long, long time ago, called "Music". Thought it was just a placeholder, but this literally coincided with the component breaking. Only realized this just now when I saw the "Discord application token" setting in your component, so I recreated the application and copypasted the token from there into the setting, installed the Discord application my user account, restarted foobar and Discord and now it works like before. I don't think one should need to create a user application on the Discord app dev panel to use this component, no? This should work by itself? I am confused.

**Comment by TheQwertiest** [comment]
Yeah, this should definitely not be required.
The only reason it might be needed is when one want to replace built-in images.
Or if for some reason my app is banned (and as far as I know it's not).
Very weird.

Or maybe some internal discord settings rely on app id for identification and they were reset for your 'new application'
