### ISSUE TITLE
Extra "on" in album title when hovering over album art

### ISSUE THREAD

**Issue by trwnh** [TheQwertiest/foo_discord_rich#60]
Running 2.0.0-beta+bbb11c2 x64 of foo_discord_rich from Appveyor CI and I'm glad to say it mostly works as expected! Just one thing: hovering over the album art displays the string "on $ALBUM" instead of just "$ALBUM".

![image](https://github.com/user-attachments/assets/31855db7-d36f-4e23-b694-b6bf6a134c3a)

It would be ideal if the hovertext instead showed the album title instead of duplicating the text of the details right next to it.

**Comment by TheQwertiest** [comment]
Regretfully, nothing I can do about it: discord uses the same text for the hover and for the middle section.

**Comment by trwnh** [comment]
Aw, rats. Thanks for the quick response!
