### ISSUE TITLE
Not always able to fetch the cover art via MusicBrainz

### ISSUE THREAD

**Issue by flowi07** [TheQwertiest/foo_discord_rich#63]
For some reason plugin can't always fetch the cover, but the metadata is all there, what could be the matter?
![foobar2000_m4YJWUtsqN](https://github.com/user-attachments/assets/6779d84d-5233-4ef5-ac38-ab68c8b50f43)

**Comment by flowi07** [comment]
Okay, I get the point. My some files just don't have the <MUSICBRAINZ_RELEASEGROUPID> metadata. I thought it was searching by album and artist name

**Comment by TheQwertiest** [comment]
It does search by artist and album :)
But it tries to search via MB album ID first, if it's present (it doesn't use any other MB id's though)

**Comment by TheQwertiest** [comment]
I'll take a look tomorrow, since error seems really weird

**Comment by flowi07** [comment]
Well, without MB metadata, the covers don't work anyway

**Comment by TheQwertiest** [comment]
Found the issue with release-group retrieval (which causes search to return wrong values), but could not reproduce weird "Code: 0" error.
Could you please send me the track from original post so that I can reproduce it?

**Comment by flowi07** [comment]
> Found the issue with release-group retrieval (which causes search to return wrong values), but could not reproduce weird "Code: 0" error. Could you please send me the track from original post so that I can reproduce it?

https://file.io/9G8RSwrbL9ju

**Comment by TheQwertiest** [comment]
I've experimented with your track a bit, but (regretfully?) could not reproduce the issue :(
Just to make sure, you are on native Windows and not using WINE, right?

PS: Album art fetching worked (somewhat) properly (though Musicbrainz thought that `SAILORWAVE III` matches better than `SAILORWAVE`...)

**Comment by flowi07** [comment]
Native Windows 10, latest version

**Comment by flowi07** [comment]
Still not working for me
![foobar2000_9WB3smg0o6](https://github.com/user-attachments/assets/9381796d-c5c9-40fb-bc70-08e8db344e88)

**Comment by flowi07** [comment]
nvm, musicbrainz.org is blocked in my country xD

**Comment by TheQwertiest** [comment]
> is blocked in my country

But... why? It's just a music archive...

I will add the option for custom musicbrainz url in the future release though.

**Comment by flowi07** [comment]
> But... why? It's just a music info archive...

I looked up what the site was blocked for, it was supposedly blocked for some "suicidal" songs. But apart from that reason, Russia could have blocked it for something else.
