### ISSUE TITLE
Embedded art is not handled correctly

### ISSUE THREAD

**Issue by okdargy** [TheQwertiest/foo_discord_rich#64]
### Issue
It seems the current version provides the cover image if it's locally stored but if it's not then it'll just pass the audio file. An example of this behavior can be seen here:
```
Uploading D:\Music\lossless\WillyRodriguezWasTaken\Bad Therapists\cover.jpg...
Uploading D:\Music\lossless\underscores\fishmonger\02. underscores - Second hand embarrassment  [QM4TX2101852].flac...
```

Currently, the [provided scripts](https://theqwertiest.github.io/foo_discord_rich/docs/advanced_users/art_upload/) in the documentation will not work reliably due to it relying on being fed only picture files and not an audio file.

### Proposal
Instead of giving the audio file to the upload command, I propose to create a **temp file** of the album art if there isn't already an existing file for the cover and pass that instead to the upload command. The temp file will then be deleted after the script returns the URL.

This would save headaches from people coming from [s0hv's version](https://github.com/s0hv/foo_discord_rich) of foo_discord_rich with their own custom upload scripts and allow them to smoothly transition to v2.0.0!

**Comment by PlaylistsTrance** [comment]
I agree with this. It also saves us from redoing the (custom) logic foobar2000 is doing to find the best cover art for the currently playing audio file.
