### ISSUE TITLE
Is there any way to change "foobar2000" to "Music" in discord 

### ISSUE THREAD

**Issue by Ascentw** [TheQwertiest/foo_discord_rich#7]
Just because "playing music" sounds better xD

**Comment by TheQwertiest** [comment]
It is possible, but I won't change it, since I want to spread the word of foobar2000 =)

**Comment by Galixte** [comment]
Hi @TheQwertiest,

is it possible to add an option in the preferences of Discord Rich for Foorbar to change the name?

**Comment by TheQwertiest** [comment]
@Galixte , displayed name is hardcoded during Discord app registration (see the link I gave you in the other issue)

**Comment by symphony** [comment]
> @Galixte , displayed name is hardcoded during Discord app registration (see the link I gave you in the other issue)

Can you post the link?
