### ISSUE TITLE
Other Discord users or my ALT account cannot see my Foobar2000's Discord rpc in my Discord status.

### ISSUE THREAD

**Issue by kridtakarn** [TheQwertiest/foo_discord_rich#8]
I have test my discord rich presence visibility from my ALT account and my main account at a browser. It could not see my status that have foobar2000 rich presence.

**Looking via a browser**
![image](https://user-images.githubusercontent.com/25052848/59155605-4f900e80-8ab7-11e9-968a-f04408ce9797.png)

**Looking via a ALT**
![image](https://user-images.githubusercontent.com/25052848/59155607-59b20d00-8ab7-11e9-9d61-3d13c55e26ec.png)

**Looking via my Discord app with my main account**
![image](https://user-images.githubusercontent.com/25052848/59155610-6f273700-8ab7-11e9-8298-884f83f829f3.png)

**Looking via my friend PC with my friend account**
![image](https://user-images.githubusercontent.com/25052848/59155618-9f6ed580-8ab7-11e9-8785-80f35c1c7627.png)

**Comment by TheQwertiest** [comment]
Could not reproduce: other users (in the desktop app at least) can see all the proper icons and appropriate text. Not sure if the browser works with Rich Display at all (does it work for other games?)

**Comment by k0zyrev** [comment]
I can sort of confirm this. When I have a custom status set, foobar shows up only in the discord desktop app, but not in the browser client.

**Comment by k0zyrev** [comment]
I can sort of confirm this. When I have a custom status set, foobar shows up only in the discord desktop app, but not in the browser client.

**Comment by k0zyrev** [comment]
So I had a chat with discord tech support, they say the problem is not on their end https://i.imgur.com/wBj8QDx.png

**Comment by TheQwertiest** [comment]
@k0zyrev , as far as I know, discord browser client does not support Rich Presence.

**Comment by BLegereSK** [comment]
So, by looking at this, could it be a problem with connecting game activity to Foobar2000? I've done that and it looked similar to the picture shown at the bottom. One thing I'll say is, don't connect game activity directly to Foobar2000. The rich presence works without that. Hopefully this helps if anyone else has this issue.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/95780444-e7989c00-0c99-11eb-8905-48fe4bd38446.png)
It doesn't work for me either.

**Comment by JDJGInc** [comment]
and this is on my own account as well.

**Comment by TheQwertiest** [comment]
@JDJGInc it seems that you've added fb2k manually via Discord's `APP SETTINGS` > `Game Activity`.
You don't need to do that. Fb2k automatically connects to the discord and displays Rich Presence when plugins is enabled.

**Comment by JDJGInc** [comment]
Ah okay.
